version: '2'

services:
  redis:
    image: 'redis:5.0.5-alpine'
    command: 'redis-server'
    ports:
      - '6379:6379' 
    networks:
      - zero_net
  rq-worker:
    image: 'rq-worker'
    networks:
      - zero_net
    command: 'rq worker -u redis://redis:6379 emailer-tasks'
    environment:
      - REDIS_URL=redis://redis:6379
    volumes: 
      - ./:/usr/src/app
  api:
    restart: always
    image: api
    build:
      context: .
    depends_on:
      - "redis"
    volumes:
      - ./:/home/api/src
    expose:
      - 5000
    ports:
      - '5000:5000'
    entrypoint: ["./boot.sh"]
    networks: 
      - zero_net
    environment:
      - FLASK_APP
      - FLASK_ENV
      - SENDGRID
      - AUTH
      - SENDGRID_ENABLED
      - SHEETS_ENABLED
      - FROM_EMAIL
      - TO_EMAIL
      - REDIS_URL=redis://redis:6379
      - STRIPE

networks:
  zero_net:
    external: true
